# Generated by Django 4.2.3 on 2023-07-30 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 30, 4, 43, 37, 274858, tzinfo=datetime.timezone.utc))),
                ('author', models.CharField(max_length=25)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tags')),
            ],
        ),
    ]
